services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data