services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  lk_service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre
      CORS_ALLOWED_HOST: localhost:3000
